// Generated by gencpp from file hello_protocol/Connection.msg
// DO NOT EDIT!


#ifndef HELLO_PROTOCOL_MESSAGE_CONNECTION_H
#define HELLO_PROTOCOL_MESSAGE_CONNECTION_H

#include <ros/service_traits.h>


#include <hello_protocol/ConnectionRequest.h>
#include <hello_protocol/ConnectionResponse.h>


namespace hello_protocol
{

struct Connection
{

typedef ConnectionRequest Request;
typedef ConnectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Connection
} // namespace hello_protocol


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hello_protocol::Connection > {
  static const char* value()
  {
    return "351d733a7219728e094fe3e87d955c3a";
  }

  static const char* value(const ::hello_protocol::Connection&) { return value(); }
};

template<>
struct DataType< ::hello_protocol::Connection > {
  static const char* value()
  {
    return "hello_protocol/Connection";
  }

  static const char* value(const ::hello_protocol::Connection&) { return value(); }
};


// service_traits::MD5Sum< ::hello_protocol::ConnectionRequest> should match 
// service_traits::MD5Sum< ::hello_protocol::Connection > 
template<>
struct MD5Sum< ::hello_protocol::ConnectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hello_protocol::Connection >::value();
  }
  static const char* value(const ::hello_protocol::ConnectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello_protocol::ConnectionRequest> should match 
// service_traits::DataType< ::hello_protocol::Connection > 
template<>
struct DataType< ::hello_protocol::ConnectionRequest>
{
  static const char* value()
  {
    return DataType< ::hello_protocol::Connection >::value();
  }
  static const char* value(const ::hello_protocol::ConnectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hello_protocol::ConnectionResponse> should match 
// service_traits::MD5Sum< ::hello_protocol::Connection > 
template<>
struct MD5Sum< ::hello_protocol::ConnectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hello_protocol::Connection >::value();
  }
  static const char* value(const ::hello_protocol::ConnectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello_protocol::ConnectionResponse> should match 
// service_traits::DataType< ::hello_protocol::Connection > 
template<>
struct DataType< ::hello_protocol::ConnectionResponse>
{
  static const char* value()
  {
    return DataType< ::hello_protocol::Connection >::value();
  }
  static const char* value(const ::hello_protocol::ConnectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HELLO_PROTOCOL_MESSAGE_CONNECTION_H
