// Generated by gencpp from file hello_protocol/ConnectionResponse.msg
// DO NOT EDIT!


#ifndef HELLO_PROTOCOL_MESSAGE_CONNECTIONRESPONSE_H
#define HELLO_PROTOCOL_MESSAGE_CONNECTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hello_protocol
{
template <class ContainerAllocator>
struct ConnectionResponse_
{
  typedef ConnectionResponse_<ContainerAllocator> Type;

  ConnectionResponse_()
    : connection_response()  {
    }
  ConnectionResponse_(const ContainerAllocator& _alloc)
    : connection_response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _connection_response_type;
  _connection_response_type connection_response;





  typedef boost::shared_ptr< ::hello_protocol::ConnectionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello_protocol::ConnectionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ConnectionResponse_

typedef ::hello_protocol::ConnectionResponse_<std::allocator<void> > ConnectionResponse;

typedef boost::shared_ptr< ::hello_protocol::ConnectionResponse > ConnectionResponsePtr;
typedef boost::shared_ptr< ::hello_protocol::ConnectionResponse const> ConnectionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello_protocol::ConnectionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello_protocol::ConnectionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hello_protocol

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hello_protocol': ['/home/anjalee/multi_robot_communication/src/hello_protocol/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hello_protocol::ConnectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_protocol::ConnectionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_protocol::ConnectionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_protocol::ConnectionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_protocol::ConnectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_protocol::ConnectionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello_protocol::ConnectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f40f78dc91c611e8de7bf165720cfb5a";
  }

  static const char* value(const ::hello_protocol::ConnectionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf40f78dc91c611e8ULL;
  static const uint64_t static_value2 = 0xde7bf165720cfb5aULL;
};

template<class ContainerAllocator>
struct DataType< ::hello_protocol::ConnectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello_protocol/ConnectionResponse";
  }

  static const char* value(const ::hello_protocol::ConnectionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello_protocol::ConnectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string connection_response\n\
\n\
";
  }

  static const char* value(const ::hello_protocol::ConnectionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello_protocol::ConnectionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.connection_response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConnectionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello_protocol::ConnectionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello_protocol::ConnectionResponse_<ContainerAllocator>& v)
  {
    s << indent << "connection_response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.connection_response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_PROTOCOL_MESSAGE_CONNECTIONRESPONSE_H
