// Generated by gencpp from file hello_protocol/Hello.msg
// DO NOT EDIT!


#ifndef HELLO_PROTOCOL_MESSAGE_HELLO_H
#define HELLO_PROTOCOL_MESSAGE_HELLO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hello_protocol
{
template <class ContainerAllocator>
struct Hello_
{
  typedef Hello_<ContainerAllocator> Type;

  Hello_()
    : Hello_from_Robot1()  {
    }
  Hello_(const ContainerAllocator& _alloc)
    : Hello_from_Robot1(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Hello_from_Robot1_type;
  _Hello_from_Robot1_type Hello_from_Robot1;





  typedef boost::shared_ptr< ::hello_protocol::Hello_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello_protocol::Hello_<ContainerAllocator> const> ConstPtr;

}; // struct Hello_

typedef ::hello_protocol::Hello_<std::allocator<void> > Hello;

typedef boost::shared_ptr< ::hello_protocol::Hello > HelloPtr;
typedef boost::shared_ptr< ::hello_protocol::Hello const> HelloConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello_protocol::Hello_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello_protocol::Hello_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hello_protocol

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hello_protocol': ['/home/anjalee/multi_robot_communication/src/hello_protocol/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hello_protocol::Hello_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_protocol::Hello_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_protocol::Hello_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_protocol::Hello_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_protocol::Hello_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_protocol::Hello_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello_protocol::Hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8916ac80101a481b96c0cfdc1217c9f";
  }

  static const char* value(const ::hello_protocol::Hello_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8916ac80101a481ULL;
  static const uint64_t static_value2 = 0xb96c0cfdc1217c9fULL;
};

template<class ContainerAllocator>
struct DataType< ::hello_protocol::Hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello_protocol/Hello";
  }

  static const char* value(const ::hello_protocol::Hello_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello_protocol::Hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Hello_from_Robot1\n\
";
  }

  static const char* value(const ::hello_protocol::Hello_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello_protocol::Hello_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Hello_from_Robot1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Hello_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello_protocol::Hello_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello_protocol::Hello_<ContainerAllocator>& v)
  {
    s << indent << "Hello_from_Robot1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Hello_from_Robot1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_PROTOCOL_MESSAGE_HELLO_H
