// Generated by gencpp from file hello_protocol/WaveResponse.msg
// DO NOT EDIT!


#ifndef HELLO_PROTOCOL_MESSAGE_WAVERESPONSE_H
#define HELLO_PROTOCOL_MESSAGE_WAVERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hello_protocol
{
template <class ContainerAllocator>
struct WaveResponse_
{
  typedef WaveResponse_<ContainerAllocator> Type;

  WaveResponse_()
    : waving_back()  {
    }
  WaveResponse_(const ContainerAllocator& _alloc)
    : waving_back(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _waving_back_type;
  _waving_back_type waving_back;





  typedef boost::shared_ptr< ::hello_protocol::WaveResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello_protocol::WaveResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WaveResponse_

typedef ::hello_protocol::WaveResponse_<std::allocator<void> > WaveResponse;

typedef boost::shared_ptr< ::hello_protocol::WaveResponse > WaveResponsePtr;
typedef boost::shared_ptr< ::hello_protocol::WaveResponse const> WaveResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello_protocol::WaveResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello_protocol::WaveResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hello_protocol

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hello_protocol': ['/home/anjalee/multi_robot_communication/src/hello_protocol/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hello_protocol::WaveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_protocol::WaveResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_protocol::WaveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_protocol::WaveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_protocol::WaveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_protocol::WaveResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello_protocol::WaveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "496fdf2ef26895dfa8463e939f855199";
  }

  static const char* value(const ::hello_protocol::WaveResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x496fdf2ef26895dfULL;
  static const uint64_t static_value2 = 0xa8463e939f855199ULL;
};

template<class ContainerAllocator>
struct DataType< ::hello_protocol::WaveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello_protocol/WaveResponse";
  }

  static const char* value(const ::hello_protocol::WaveResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello_protocol::WaveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string waving_back\n\
\n\
";
  }

  static const char* value(const ::hello_protocol::WaveResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello_protocol::WaveResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waving_back);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaveResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello_protocol::WaveResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello_protocol::WaveResponse_<ContainerAllocator>& v)
  {
    s << indent << "waving_back: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.waving_back);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_PROTOCOL_MESSAGE_WAVERESPONSE_H
